### ISSUE TITLE
Viewing temperature on Home Assistant

### ISSUE THREAD

**Issue by justin1977justin** [theyosh/TerrariumPI#390]
I have looked through all of the past issues in an attempt to resolve this myself but i am unable to figure it out. I have Home Assistant running and would like to be able to view one of my terrarium temperatures on it. I really have no idea how to begin. I have setup a sensor in home assistant trying to get cpu temperature as a start thinking that would be the easiest thing to setup. I used an example that i found for a reef controller and adjusted it to the following which is the only config that i have found that will actually show as a sensor in HA. However, the state just shows as {}. Has anyone incorporated this with HA and can point me in the right direction?

```
   - platform: rest
      name: ClaytonGecko Temperature
      username: !secret GeckoUN
      password: !secret GeckoPW
      authentication: basic 
      json_attributes:
        - cpu_temperature
      resource: http://terrariumpi_ip_address:8090/api/info
      headers:
          Connection: keep-alive
          content-type: application/json
```
